# Generated by Django 4.1.2 on 2022-10-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=300)),
                ('definition', models.TextField()),
                ('photo1', models.ImageField(upload_to='media/img')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='media/img')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='media/img')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='media/img')),
                ('price', models.FloatField(default=0.0)),
                ('count', models.PositiveIntegerField(default=1)),
                ('delivery_price', models.FloatField(default=0.0)),
            ],
        ),
    ]
