# Generated by Django 4.1.2 on 2022-10-08 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_product_users_alter_product_photo1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='users',
        ),
        migrations.AddField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
