# Generated by Django 4.1.2 on 2022-10-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_users_product_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bio',
            field=models.CharField(max_length=50),
        ),
    ]
