# Generated by Django 4.1.2 on 2022-10-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy',
            field=models.BooleanField(default=0),
        ),
    ]
